### ISSUE TITLE
Animating table/collection updates

### ISSUE THREAD

**Issue by russbishop** [Swift-Flow/Swift-Flow#22]
Trying to implement the proper animating in of sections (as Photos framework queries process in the background and I update a `UICollectionView`), I am running into some problems.

I track my pending changes which are part of the app state. In `newState` I look for those and if found I process them in a `performBatchChanges` block on the collection view. At the end I dispatch a `PhotoActions.PendingChangesHandled(changes)` action to notify the store. I'll call this the ACK message for brevity. 

At that point the app dies because I'm dispatching while in the middle of a dispatch. 

Here are the potential solutions as I see them:

1. Dispatch to a background queue, then from there dispatch back to the main queue, then dispatch the ACK. This introduces logic errors because the Photos framework query is still being processed and sending even further updates asynchronously but the pending changes array in the app state hasn't had the resolved changes removed. So if one of those further state changes slips in-between, the collection view will attempt to re-apply pending changes it has already applied and Bad Things™ will happen.

2. The store can perform a completion block but the problem is this is really communication between the VC and Store of something it did after the fact so it would require the action creator, VC, and store/reducers to collude in a really tangled way. This seems like it is just a path to re-introduce complexity.

3. Have the VC flip a property on the `PendingChange` object to mark it as handled. This is gross because it directly contradicts the spirit behind the framework by having the view controller mutate app state directly... besides the fact that doing this in other scenarios could introduce race conditions and various other concerns.

4. Have the VC remember `PendingChange` objects it has seen and ignore them on further state updates, and combine this with (1) to eventually clean old ones out of the list. This is just introducing mutable state back into the VC

5. Add a facility to inject a post-dispatch completion function which the VC could use to make sure its ACK was sent after dispatch was finished but before any new actions were processed. I'm leaning towards this only because it is easy to implement and I need to get this project out the door :) 

6. If you really wanted to get fancy the VC could compare the old state to the new state and figure out what sections or objects were added, removed, moved, etc, then animated those changes to match. That's a fairly ambitious undertaking but would align closer to what React is doing with Virtual DOM updates.

Maybe I'm over-thinking it? If you're using React then you avoid the problem by Virtual DOM diffing which makes computing the delta between (old state -> rendered view) and (new state -> rendered view) really cheap (though I haven't seen anyone take it a step further and apply animation rules based on the Virtual DOM diffs).

I thought about having a mechanism specifically to allow the view layer to acknowledge actions for cases like this. I don't know if this is a problem that will come up in other situations or if it is very specific to handling animations (which are stateful by nature). 

(6) just begs for a virtual UIKit system akin to React's Virtual DOM to generalize it but that would be a massive undertaking.

**Comment by krzysztofzablocki** [comment]
Some resources that might be helpful for 6: [SimpleDiff from Bond](https://github.com/SwiftBond/Bond/blob/8e2dbaafd33e2977be84b604db4d5b211497d16a/Bond/Core/SimpleDiff.swift) and [More complex diff from RxSwift](https://github.com/ReactiveX/RxSwift/blob/develop/RxDataSourceStarterKit/Differentiator.swift)

**Comment by russbishop** [comment]
@krzysztofzablocki Thanks, I'll take a look!


P.S. I loved your Line Drawing algorithm and that episode of Debug you did.

**Comment by Ben-G** [comment]
@russbishop This is actually an error in my implementation! I'm sorry. In this redux-style implementation of the store it is allowed to dispatch at anytime **except** inside of a reducer. Dispatching in a store observer, in response to an action is (or should be) fine! 

I will push a fix for this and that might solve your problem.

**Comment by Ben-G** [comment]
Aforementioned issue fixed by #23 and fix is available in Release 0.2.1. Let me know if this allows you to implement animations in the way you originally intended. Animations are an interesting topic in general!

**Comment by russbishop** [comment]
@Ben-G This does solve the dispatching problem but I'm going to remove the `PendingChanges` implementation since the state diffing logic works well and is more "pure".

**Comment by Ben-G** [comment]
Great! Would love to see your approach when it's done!
