### ISSUE TITLE
[Question] How to receive newState changes for a substate stored in an array ?

### ISSUE THREAD

**Issue by onekiloparsec** [Swift-Flow/Swift-Flow#388]
I've read most of the repo issues, and I still can't wrap my head around that stuff entirely.

I have an app with multiple (similar document-like) windows. I want to store the state for the app, but also for individual windows. Quite simple would you say:

```swift
struct AppState: StateType {
    ...
    var mainWindowStates: [MainWindowState] = []
}

class MainWindowState: NSObject, StateType {
    ...
    @objc var selectedIndexPaths: [IndexPath] = []
}
```

The app reducer:
```swift
func appReducer(action: Action, state: AppState?) -> AppState {
    var newState = state ?? AppState()
    ...
    newState.mainWindowStates = mainWindowStateReducer(action: action, state: newState. mainWindowStates)
    .... 
    return newState
}
```

In a view controller: 
```swift
    override func viewDidAppear() {
        super.viewDidAppear()
        mainStore.subscribe(self) { subscription in
            // using little helper function to find the MainWindowState from the windowController...
            subscription.select { state in state.windowState(for: self.windowController)! }
        }
    }
        
    func newState(state: MainWindowState) {
        // Normally, I should receive changes of selectedIndexPaths for that particular window.
        // But I don't.
    }
```

In fact, I first tried not with an array of `[MainWindowState]` but a dictionary, to no avail. I tried also many forms of the reducer function: by re-assigning the whole `mainWindowStates` array, or by changing only the relevant part of it (and of course, by changing the relevant MainWindowState itself). I never get notified of the changes. There is something I don't get.

Should I make the `mainWindowStates` conform to `StateType` ?
Thanks a lot for any help!

**Comment by DivineDominion** [comment]
Do you need the window's states shared in the app? In TableFlip (where I use `KPCTabsControl` btw :)) I create a `Store` and root `DocumentState` instance for each `NSDocument`. I also have a global `AppState` for e.g. storing app license info and pass the info to each document controller in the app.

No matter the overall approach your subscription code should still work. Can you confirm (debug print) that the `mainStore.subscribe` is called, and that the `select` is triggered at all? Is `mainWindowStates` non-empty? Does `windowState(for:)` in fact return non-nil values? Did you opt-in to "skip repeats" in your store setup and does `[MainWindowState]` conform to `Equatable` in an odd way so that substate changes are skipped?

**Comment by onekiloparsec** [comment]
At the moment, I don't need to share the various `MainWindowStates` across the app, but in the future I plan to use it. Hence, I would like to keep them nested inside tha `appState`.

Yes, the `mainStore.subscribe` is called, the `select` is triggered etc etc. No "skip repeats" whatsoever etc.

The only tricky thing a bit special is that `MainWindowState` is a class, with an `@objc` property, because I want to bind some other stuff on it.

I've tried to override the `func ==` of Equatable but with no results. This really puzzles me.

(I'm glad `KPCTabsControl` keeps being used not only in my apps :-).

**Comment by onekiloparsec** [comment]
Ok, this special thing (with the `@objc` property) is the cause of the problem. If I remove the binding, and remove the `@objc` thing, it works.

**Comment by DivineDominion** [comment]
Ah right! NSObject and @objc properties aren't value types anymore. I have no clue what will happen exactly in that case.

Will you be using this in an open source app? We're always on the lookout for code to point to as implementation samples.

**Comment by onekiloparsec** [comment]
That's not an open-source app, unfortunately. That's the v2 of my flagship app, iObserve, sorry.
