### ISSUE TITLE
Why we need to cast all the time?

### ISSUE THREAD

**Issue by soapsign** [Swift-Flow/Swift-Flow#39]
I would like to know why we need to cast all the time?
Can we eliminate the necessary of this casting?

**Comment by Ben-G** [comment]
Hi! Are you referring to casts when accessing the state of the store? This is actually changing with #37, it introduces a generic state for the store. I've moved back on forth on this for several reasons, but have decided to move forward with the generic store.

Will be fixed soon!

I'll close the issue, but let me know if you have any more questions!

**Comment by Ben-G** [comment]
Actually, it makes more sense to keep this open until the PR is merged :smile:
